name: sc_foundation_evals
channels:
  - nvidia/label/cuda-11.7.0
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit
  - r-base=4.2.3
  - ninja
  - rpy2
  - packaging
  - gxx=11.4
  - git-lfs
  - pip>=21.1
  - pip:
    - --index-url https://download.pytorch.org/whl/cu117
    - torch==1.13
    - torchvision
    - torchaudio
